; VoiceBooth installer for Windows (Inno Setup 6.5.2 or later). DESIGN 11.6.
;
; Unsigned for now: SmartScreen shows "Windows protected your PC" -> "More info" -> "Run anyway".
; Code signing comes after the signing entity is decided (DESIGN 19).
;
; Build (from the repository root, after the Release build):
;   ISCC /DAppVersion=0.1.0 packaging\windows\VoiceBooth.iss
; or let packaging\windows\build_installer.ps1 find ISCC and read the version from build\CMakeCache.txt.
;
; Optional /D overrides:
;   AppVersion  version string (required; CMake PROJECT_VERSION, numeric x.y.z)
;   AppBuildDir folder that contains VoiceBooth.exe (default: build\VoiceBooth_artefacts\Release)
;   OutputDir   where the setup .exe is written (default: build\installer)
;
; Keep this file ASCII-only (no encoding surprises in ISCC).

; PNG wizard images need 6.5.2+ (earlier versions accept .bmp only).
#if Ver < EncodeVer(6, 5, 2)
  #error Inno Setup 6.5.2 or later is required (PNG wizard images)
#endif

#ifndef AppVersion
  #error AppVersion is not defined. Pass /DAppVersion=<CMake PROJECT_VERSION>
#endif

#define AppName       "VoiceBooth"
#define AppPublisher  "SEVENTHWELL"
#define AppURL        "https://github.com/kajisho5/voicebooth"
#define AppExeName    "VoiceBooth.exe"

; SourcePath = folder of this script (with trailing backslash)
#define RepoRoot      SourcePath + "..\.."
#define BrandDir      RepoRoot + "\brand\out"

#ifndef AppBuildDir
  #define AppBuildDir RepoRoot + "\build\VoiceBooth_artefacts\Release"
#endif
#ifndef OutputDir
  #define OutputDir   RepoRoot + "\build\installer"
#endif

#if !FileExists(AppBuildDir + "\" + AppExeName)
  #error VoiceBooth.exe not found in AppBuildDir. Build Release first (cmake --build build --config Release)
#endif

[Setup]
; AppId must never change: Windows uses it to find the existing install for upgrades / uninstall.
AppId={{E17D5960-64DF-4D1A-832E-C8DC4510D36B}
AppName={#AppName}
AppVersion={#AppVersion}
AppVerName={#AppName} {#AppVersion}
AppPublisher={#AppPublisher}
AppPublisherURL={#AppURL}
AppSupportURL={#AppURL}/issues
AppUpdatesURL={#AppURL}/releases
AppCopyright=Copyright (C) {#AppPublisher}. AGPL-3.0-or-later
VersionInfoVersion={#AppVersion}
VersionInfoProductName={#AppName}
VersionInfoDescription={#AppName} Setup

; Per-user install by default (no admin / UAC prompt): {autopf} = %LOCALAPPDATA%\Programs.
; "setup.exe /ALLUSERS" installs for all users into Program Files instead (asks for admin).
PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=commandline
DefaultDirName={autopf}\{#AppName}
DisableProgramGroupPage=yes
UsePreviousAppDir=yes
ShowLanguageDialog=auto

; x64 only. Windows 10 1607 or later (DESIGN 11.6.1)
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
MinVersion=10.0.14393

; AGPL-3.0-or-later text shown on the license page
LicenseFile={#RepoRoot}\LICENSE

SetupIconFile={#BrandDir}\icons\VoiceBooth.ico
UninstallDisplayIcon={app}\VoiceBooth.ico
UninstallDisplayName={#AppName}
WizardStyle=modern
; Setup picks the file that best matches the DPI
WizardImageFile={#BrandDir}\installer\installer-wizard.png,{#BrandDir}\installer\installer-wizard@2x.png
WizardSmallImageFile={#BrandDir}\installer\installer-small.png,{#BrandDir}\installer\installer-small@2x.png

OutputDir={#OutputDir}
OutputBaseFilename=VoiceBooth-{#AppVersion}-win-x64-setup
Compression=lzma2/max
SolidCompression=yes

; Close a running VoiceBooth before replacing files
CloseApplications=yes
RestartApplications=no

; .vbooth (project file, DESIGN 8 / B14) opens in VoiceBooth; the document uses the app icon
ChangesAssociations=yes

[Languages]
; Picked from the Windows UI language; the language dialog appears only when it matches neither.
; The first entry is the fallback.
Name: "english";  MessagesFile: "compiler:Default.isl"
Name: "japanese"; MessagesFile: "compiler:Languages\Japanese.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "{#AppBuildDir}\{#AppExeName}"; DestDir: "{app}"; Flags: ignoreversion
; Vocal separation process and ONNX Runtime (MIT), built next to the app (DESIGN 11.3 / B16). The model itself is downloaded on request
Source: "{#AppBuildDir}\VoiceBoothSeparator.exe"; DestDir: "{app}"; Flags: ignoreversion skipifsourcedoesntexist
Source: "{#AppBuildDir}\onnxruntime.dll"; DestDir: "{app}"; Flags: ignoreversion skipifsourcedoesntexist
Source: "{#AppBuildDir}\onnxruntime_providers_shared.dll"; DestDir: "{app}"; Flags: ignoreversion skipifsourcedoesntexist
; Hand-tuned 16/24/32/48 icon (brand/README: the .exe icon is generated by JUCE)
Source: "{#BrandDir}\icons\VoiceBooth.ico"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#RepoRoot}\LICENSE"; DestDir: "{app}"; DestName: "LICENSE.txt"; Flags: ignoreversion
; License texts of the bundled components (JUCE, Rubber Band, ONNX Runtime, Monocypher, minimp3, IBM Plex, ASIO SDK), collected by CMake (#15)
Source: "{#AppBuildDir}\licenses\*"; DestDir: "{app}\licenses"; Flags: ignoreversion recursesubdirs

[Icons]
Name: "{autoprograms}\{#AppName}"; Filename: "{app}\{#AppExeName}"; IconFilename: "{app}\VoiceBooth.ico"
Name: "{autodesktop}\{#AppName}"; Filename: "{app}\{#AppExeName}"; IconFilename: "{app}\VoiceBooth.ico"; Tasks: desktopicon

[Run]
Filename: "{app}\{#AppExeName}"; Description: "{cm:LaunchProgram,{#AppName}}"; Flags: nowait postinstall skipifsilent

; Settings, takes and downloaded models live in the user's data folder and are kept on uninstall
; (the user's recordings must never be deleted by the uninstaller).

[Registry]
; .vbooth association (per user or per machine, following the install mode)
Root: HKA; Subkey: "Software\Classes\.vbooth"; ValueType: string; ValueName: ""; ValueData: "VoiceBooth.Project"; Flags: uninsdeletevalue
Root: HKA; Subkey: "Software\Classes\.vbooth\OpenWithProgids"; ValueType: string; ValueName: "VoiceBooth.Project"; ValueData: ""; Flags: uninsdeletevalue
Root: HKA; Subkey: "Software\Classes\VoiceBooth.Project"; ValueType: string; ValueName: ""; ValueData: "VoiceBooth Project"; Flags: uninsdeletekey
Root: HKA; Subkey: "Software\Classes\VoiceBooth.Project\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\{#AppExeName},0"
Root: HKA; Subkey: "Software\Classes\VoiceBooth.Project\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\{#AppExeName}"" ""%1"""
